import cv2
import os

# --- CONFIGURATION (CUSTOMIZE THESE PATHS) ---
# Point these to the folders your Slay the Spire mod is saving to!
IMAGE_DIR = r"C:/Users/andre/Documents/GitHub/Sts_Automatization/output/gen_screen_images"
LABEL_DIR = r"C:/Users/andre/Documents/GitHub/Sts_Automatization/output/gen_screen_labels"
CLASSES_FILE = r"C:/Users/andre/Documents/GitHub/Sts_Automatization/output/gen_screen_classes.txt"

# Where you want the debug images with drawn boxes to be saved
OUTPUT_DIR = r"C:/Users/andre/Documents/GitHub/Sts_Automatization/output/debug_visualized"

def main():
    # Create the output directory if it doesn't exist
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 1. Load the class dictionary so we can read the actual names
    classes = {}
    if os.path.exists(CLASSES_FILE):
        with open(CLASSES_FILE, 'r') as f:
            for i, line in enumerate(f.readlines()):
                classes[i] = line.strip()
    else:
        print(f"Warning: Could not find {CLASSES_FILE}. Using raw ID numbers instead.")

    # 2. Loop through every image generated by the mod
    for filename in os.listdir(IMAGE_DIR):
        if not filename.endswith((".png", ".jpg", ".jpeg")):
            continue

        img_path = os.path.join(IMAGE_DIR, filename)
        label_name = os.path.splitext(filename)[0] + ".txt"
        label_path = os.path.join(LABEL_DIR, label_name)

        # Read the image
        img = cv2.imread(img_path)
        if img is None:
            continue

        h, w, _ = img.shape

        # 3. Read the YOLO labels and draw the boxes
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                lines = f.readlines()

            for line in lines:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue

                class_id = int(parts[0])
                x_center, y_center, bbox_w, bbox_h = map(float, parts[1:])

                # Convert YOLO normalized math [0 to 1] back into absolute screen pixels
                abs_x = int((x_center - bbox_w / 2) * w)
                abs_y = int((y_center - bbox_h / 2) * h)
                abs_w = int(bbox_w * w)
                abs_h = int(bbox_h * h)

                # Draw the bounding box (Bright Green, 2px thick)
                cv2.rectangle(img, (abs_x, abs_y), (abs_x + abs_w, abs_y + abs_h), (0, 255, 0), 2)

                # Get the name of the object (e.g., "Card_Strike_R" or "Enemy_JawWorm")
                class_name = classes.get(class_id, str(class_id))

                # Draw the text label just above the box (Red text)
                cv2.putText(img, class_name, (abs_x, max(abs_y - 5, 15)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

        # Save the drawn image to the output folder
        out_path = os.path.join(OUTPUT_DIR, filename)
        cv2.imwrite(out_path, img)
        print(f"Saved debug image: {filename}")

    print("/nAll bounding boxes visualized")

if __name__ == "__main__":
    main()